# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f64d2bcde22678bf8903bba04da37b99dfec3c83c2448751d8f58dc44ee0451476e8f6a4aaead4e7b0465d62d9aadde33f54f866ab5ba8614f5c081f5c988826

test:
  secret_key_base: 1373c6f2e3aaec5621e4813e41cda1cd201f1f1d79226c656f7792634a52b52ca16689be5e065e3eb29ca571c3c7164b0eb2ecc90c18d9530de63c118a58bc73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
